### ISSUE TITLE
GitHub transfer checklist

### ISSUE THREAD

**Issue by LindsayYoung** [fecgov/fec-transition#155]
## Repos that need ownership transfered

- [x] [FEC](https://github.com/18F/fec): a general discussion forum. We [compile feedback](https://github.com/18F/fec/issues) from the FEC.gov feedback widget here, and this is the best place to submit general feedback.
    - [x] add new web hook for the GitHub comment tool in the cf env vars 
- [x] [openFEC](https://github.com/18F/openfec): the first RESTful API for the Federal Election Commission
    - [x]  set up circle (there are a lot of env vars for this repo)
    - [x] set up Slack web hooks
    - [x] set up gemnasium alerts
    - [x] confirm code coverage ports over
- [x] [fec-eregs](https://github.com/18F/fec-eregs): the FEC's new Code of Federal Regulations explorer
    - [x]  set up circle
    - [x] set up Slack web hooks
    - [x] set up gemnasium alerts
- [x] [fec-cms](https://github.com/18F/fec-cms)
   - [x] set up circle  
   - [x] set up gemnasium alerts
- [x] [fec-proxy](https://github.com/18F/fec-proxy): the proxy application to manage and route requests coming to the new FEC.gov site
- [x] [fec-infrastructure](https://github.com/18F/fec-infrastructure): manages the gov cloud RDS
    - [x]  set up circle
- [x]  [fec-pattern-library](https://github.com/18F/fec-pattern-library)
    - [x]  set up circle 
    - [x] set up gemnasium alerts 
- [x] [fec-testing](https://github.com/18F/fec-testing)
- [x] [fec-epics](https://github.com/18F/fec-testing)
- [x] [fec-transition](https://github.com/18F/fec-transition)

After those are finished do a sweep to make sure the docs are point to the right place
- [x] Update documentation links 

The accounts repo should be private, so FEC will need a private account- would want to confirm that can be procured before transferring

**Comment by patphongs** [comment]
Let's update the wiki's and google docs in this separate ticket: https://github.com/fecgov/fec-transition/issues/196

**Comment by LindsayYoung** [comment]
🎉🇺🇸 public GitHub transfered to FEC 🇺🇸🎉
