### ISSUE TITLE
Accounts transfer checklist

### ISSUE THREAD

**Issue by LindsayYoung** [fecgov/fec-transition#195]
# List of Accounts to transfer

- [ ] GitHub
    - [ ] free repos https://github.com/fecgov/fec-transition/issues/155
    - [ ] fec-accounts (requires paid account)
- [ ] New Relic
   - [ ] purchase https://github.com/fecgov/fec-transition/issues/138
   - [ ] set up APM and synthetics
- [ ] AWS https://github.com/fecgov/fec-transition/issues/137
- [x] Circle (This is taken care of in the GitHub transfer)
- [x] Cloud.gov
- [x] Kabana
- [x]  api.data.cloud.gov
